# Generated by Django 4.1.7 on 2023-03-26 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GameAgeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_age_rating_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GameDetails',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=100)),
                ('game_description', models.CharField(max_length=1000)),
                ('game_spotlight_image', models.ImageField(upload_to='game_spotlight_images')),
                ('game_image', models.ImageField(upload_to='game_images')),
                ('game_video', models.FileField(upload_to='game_videos')),
                ('game_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('game_rating', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('game_release_date', models.DateField()),
                ('game_genre', models.CharField(choices=[], max_length=100)),
                ('game_publisher', models.CharField(max_length=100)),
                ('game_developer', models.CharField(max_length=100)),
                ('game_platform', models.CharField(choices=[], max_length=100)),
                ('game_language', models.CharField(max_length=100)),
                ('game_system_requirements', models.CharField(max_length=1000)),
                ('game_tags', models.CharField(default='None', max_length=1000)),
                ('game_age_rating', models.CharField(choices=[], max_length=100)),
                ('game_link', models.CharField(max_length=1000)),
                ('game_status', models.CharField(choices=[], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GameStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_status_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GameTrailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer', models.FileField(upload_to='game_trailers')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playcenter.gamedetails')),
            ],
        ),
        migrations.CreateModel(
            name='GameScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='game_screenshots')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playcenter.gamedetails')),
            ],
        ),
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('review_date', models.DateField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playcenter.gamedetails')),
            ],
        ),
    ]
