# Generated by Django 4.1.7 on 2023-03-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playcenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetails',
            name='game_age_rating',
            field=models.CharField(choices=[('Everyone', 'Everyone'), ('Teen', 'Teen'), ('Mature', 'Mature')], max_length=100),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='game_platform',
            field=models.CharField(choices=[('PC', 'PC'), ('Xbox', 'Xbox'), ('PlayStation', 'PlayStation'), ('Nintendo', 'Nintendo'), ('Android', 'Android'), ('iOS', 'iOS'), ('Other', 'Other')], default='PC', max_length=100),
        ),
    ]
