# Generated by Django 4.1.7 on 2023-03-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playcenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetail',
            name='game_genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Arcade', 'Arcade'), ('Board', 'Board'), ('Card', 'Card'), ('Casino', 'Casino'), ('Educational', 'Educational'), ('Family', 'Family'), ('Music', 'Music'), ('Puzzle', 'Puzzle'), ('Racing', 'Racing'), ('Role-Playing', 'Role-Playing'), ('Shooter', 'Shooter'), ('Simulation', 'Simulation'), ('Sports', 'Sports'), ('Strategy', 'Strategy'), ('Trivia', 'Trivia'), ('Word', 'Word'), ('Other', 'Other')], default='Action', max_length=100),
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='game_language',
            field=models.CharField(choices=[('English', 'English'), ('French', 'French'), ('German', 'German'), ('Spanish', 'Spanish'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Chinese', 'Chinese'), ('Russian', 'Russian'), ('Other', 'Other')], default='English', max_length=100),
        ),
    ]
