# Generated by Django 4.1.7 on 2023-03-26 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playcenter', '0002_alter_gamedetails_game_age_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Developer',
        ),
        migrations.DeleteModel(
            name='GameAgeRating',
        ),
        migrations.DeleteModel(
            name='GameStatus',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.AddField(
            model_name='gamedetails',
            name='game_created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='gamedetails',
            name='game_updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='game_age_rating',
            field=models.CharField(choices=[('3+', '3+'), ('7+', '7+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], default='3+', max_length=100),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='game_genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Arcade', 'Arcade'), ('Board', 'Board'), ('Card', 'Card'), ('Casino', 'Casino'), ('Educational', 'Educational'), ('Family', 'Family'), ('Music', 'Music'), ('Puzzle', 'Puzzle'), ('Racing', 'Racing'), ('Role-Playing', 'Role-Playing'), ('Shooter', 'Shooter'), ('Simulation', 'Simulation'), ('Sports', 'Sports'), ('Strategy', 'Strategy'), ('Trivia', 'Trivia'), ('Word', 'Word'), ('Other', 'Other'), ('MMO', 'MMO'), ('MOBA', 'MOBA'), ('Roguelike', 'Roguelike')], default='Action', max_length=100),
        ),
        migrations.AlterField(
            model_name='gamedetails',
            name='game_status',
            field=models.CharField(choices=[('Coming Soon', 'Coming Soon'), ('Early Access', 'Early Access'), ('Released', 'Released'), ('Cancelled', 'Cancelled'), ('Beta', 'Beta'), ('Alpha', 'Alpha'), ('Demo', 'Demo')], default='Coming Soon', max_length=100),
        ),
    ]
