# Generated by Django 4.1.7 on 2023-03-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playcenter', '0002_alter_gamedetail_game_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetail',
            name='game_image',
            field=models.ImageField(unique=True, upload_to='game/images/game_images'),
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='game_spotlight_image',
            field=models.ImageField(unique=True, upload_to='game/images/game_spotlight_images'),
        ),
    ]
