# Generated by Django 4.1.7 on 2023-03-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playcenter', '0003_alter_gamedetail_game_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedetail',
            name='game_short_description',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
