# Generated by Django 4.1.7 on 2023-04-01 15:29

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playcenter', '0004_gamedetail_game_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetail',
            name='game_image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), unique=True, upload_to='game/images/game_images'),
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='game_spotlight_image',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), unique=True, upload_to='game/images/game_spotlight_images'),
        ),
    ]
