# Generated by Django 4.1.7 on 2023-03-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playcenter', '0004_alter_gamedetails_game_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetails',
            name='game_link',
            field=models.URLField(max_length=1000),
        ),
    ]
