# Generated by Django 4.1.7 on 2023-04-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playcenter', '0005_alter_gamedetail_game_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedetail',
            name='game_size',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
