# Generated by Django 4.1.7 on 2023-03-26 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playcenter', '0005_alter_gamedetails_game_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamedetails',
            old_name='game_image',
            new_name='game_image2023032617103132773',
        ),
        migrations.RenameField(
            model_name='gamedetails',
            old_name='game_spotlight_image',
            new_name='game_spotlight_image2023032617103194',
        ),
    ]
