# Generated by Django 4.1.7 on 2023-04-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playcenter', '0006_gamedetail_game_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamedetail',
            options={'ordering': ['-game_created_date']},
        ),
    ]
