"""
Django settings for playcenter_api project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from os import getenv

# load environment variables
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--*m(7@go)l&uigvv4+0fqxifo85e-jmyikilnja^s_te$=cy*e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = getenv('DEBUG')

ALLOWED_HOSTS = getenv('ALLOWED_HOSTS').split(',')


# Application definition

INSTALLED_APPS = [
    # third party apps
    'whitenoise.runserver_nostatic',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'djongo',
    'oauth2_provider',
    'django_celery_beat',


    # local apps
    'account',
    'api',
    'home',
    'playcenter',

    # django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'cloudinary_storage',
    'cloudinary'
]

MIDDLEWARE = [
    # third party middleware
    'corsheaders.middleware.CorsMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

    # django middleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'oauth2_provider.backends.OAuth2Backend'
]

ROOT_URLCONF = 'playcenter_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'account.context_processors.get_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'playcenter_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': getenv('DB_NAME'),
        'ENFORCE_SCHEMA': False,
        'CLIENT': {
            'host': getenv('DB_HOST_STRING'),
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'

# Comment out the following line if you are not using Cloudinary
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST FRAMEWORK

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# Other settings

SITE_NAME = 'Playcenter Games'

SECURE_SSL_REDIRECT = getenv('SECURE_SSL_REDIRECT')

DOMAIN_NAME = getenv('DOMAIN_NAME')

AUTH_USER_MODEL = "account.User"

CSRF_TRUSTED_ORIGINS = getenv('CSRF_TRUSTED_ORIGINS').split(',')


# OAUTH2

OAUTH2_PROVIDER = {
    "OIDC_ENABLED": True,
    # "OIDC_USERINFO": "oidc_provider.views.UserInfoView",
    # "OIDC_RSA_PRIVATE_KEY": getenv("OIDC_RSA_PRIVATE_KEY"),
    "OIDC_RSA_PRIVATE_KEY": '''
-----BEGIN RSA PRIVATE KEY-----
MIIJJwIBAAKCAgEArYopzzKXsySBZftZc2K1aN1HXeIWCP0y2dwZp14u36tKh0Sq
9W/uI3IyuyUBrnyrf3hjhaeZH6MabFZyD2mX+U6JufyQIERdLSW1v8EFeXAlZu1R
4qQe5eaHIw6micaSqhXQSFxMvo8f/2JKQHHKQZLb5mvlk1/Xy6ABbYL+yLi8+RCw
ZCxUZQli4zG7ej/uFSxnpFbA+lCqnmDABvwuZhat+fgR2t3isv68ile4KCthY8xK
wEZ2cf31rYo6dgaHjs9mEhdQ8QqBgEO2qtrafJqcvc6lMIfjHJe8OUC9zzEJ+o3l
BnbkaSlOnoV/hOpbWiRE/VL0NDjd0Y/3qSPjGz+WskGe/qkQ4MlGg0szTq43/9xv
grydPcL9b8+5kGokwm+BDMLdC2ZL5ScjtdbEMUdofmi6voayY2CNWYbK2czp+oZA
H77Ns4+CeyjwyWlovLBhN5FZXiQXUNv5WJ1xXgXcRqbikUUUTVEnfYjy7rENUshq
2QkeChDpKCUw65fxQuG5rQmLq6RKq9A/PysDe+as8kz4Hu1J0QK/yRfF9iIyEj8W
YPdXY7Lbscc0rXULcfK3F8RhiaQgBYvhqo7xS7y2QXhcMNSikRm3HnocP95JeJDR
nV/0G5mTE6cMaLLfca4WWATzYFxZKB9FspPAqwJ6fPXKoSRqwrsntNOCLNMCAwEA
AQKCAgAKAmIO9VgSmRRtkWXDZfoYpkqre5LRyejY7/z6zk/dzr9pteg2Z9JQcRHE
AYprSf2KSKNU3inSzVGE1ieWA/0kAAeploupkMffBsHI4ZUzP+ioWx/R9q1hjT5W
I04vvChRbxioU8qJYy/xRvYJaYbE6XeNfsOrEGgd8oiijF+trBoaM4A5BuWHPldZ
y1CI6I8O4ZTIwcg3p9dvcx0gSgNTGBPIyyoceZfNwyuUvyJ8DqR7YRkepfHG+WLm
M4bTr+S5s/SrLnUYsgZuI3mxuRXJAhHwUK7ucagDyiytELLh9G4i6XRAPzNFbYB/
XCvSusGyHU1tXw9+w5jnsWoTc2Jx44Z9XcETRZvCn9PLKwQ8yjmuzkECZMWRWQ/z
50W++0prfodMXbCJDnLM+nf42p8VbpTQ4PatHO9bNzCDZ0cY78JIkw/vyrqjYowA
HCCn1F/oD5j5brmziyEoKUi4xWUHI1deCl4nOQdzqbDRmgI9f2x+SZz7D4QNBebi
Jmk78pczJFS1HMJimBmLqi9ilNzy6xixgcLpaCwq777s2Gg/XPx4xFecxeCILnJM
pfdPEjK146t6khcehZ7AO7z3PtdYViqwESazYmbVnnMp545QUlQihLPczS4VaU3s
iR+LuD3DTgmahuaJRlnqdXN9+1+K8jeptUUHWxGPcCnycpefwQKCAQEA4XHRS7tC
A3kkMwBIlJoeqpk+46NuP3szM/s17sOotypad4RiLmhQxLnMEBJYN4XlyritZVIV
ZeBHfVkf5AkLnI/jEk5JWo8ExS56xCfmVMoohfinaccq/3AwZNBaf9ccYuY55100
747to+pus2vCB57nvXHmNN/KVOvEObY+xJlXR2R9TstSigHf+zJBc5UhvwfTqHL7
qNAcPXW5VRjXJqNX+AUMSwedcUDtbO5D7ck6QMZ/Vaf3POPSfTslJ04zDMBA5xJR
MNTAb/n9FdYUDKD0mJVQKw5QVnY5YwkbOHVU/Q7WJtIqLWzc5wU4T2vDzvR/w7hM
oECkNS/JG/LFywKCAQEAxQ9q1PIGa6+PX+5BS6Ij7YKCq1UcfsLP3cCaXxaIAFxI
eunHOnTQXzXCllOC1J1ggSPMSZoYOSt+3UM4S6EDF3tjwWMmqw5RyqQCAqrR8bD4
bprhcdswYL6+PAtTTj4dT6AUwfInkGVcWTogQEXrzd4vCArIQ6Scyp/tLZ7Q3fdc
3uFqJPpdRM5dmCmnjb6Nn2irEr9v/noJkWviS2gOpSbauvyqt982NPmko7ETjRkI
8GzJW+sa4vMzs4wKs1BBwv1vpbCCGtl2XdV8xYMhwI+JD18lUFV//llo0sV7APN9
JS8FOERqrXzmN5Pz+kXYuXEihD1cXaJ/7ivBsOsUGQKCAQBSeDZeA8RkTN5nIcVr
Ru3M7n5I+7IK2uCiNVVHYJ/JUV8CtZTM8TAKpwT1JCDNPtgOznvvwpU9TUwZmI7H
9l8fCKvCOI0w6XyPPS9/rjDd943XZFypn0glZT7uwiE4/tHNg/bOohQJRjm8arfQ
Pq0d6I1RiebylKMJaa3AhuBzPrzkyufj+RDal1D+LSYwR++uWAifaGCTIn4SJYyE
iq+53KsDeaVDlSeNFHlGDesfgysiIvrVtLoGtjh7wzUWKc8W7QVRAixdNpam38Yr
RMLU09RmNMi812GgH2NizSP+BT3vzIuea+ct8tLkV85/jyZ0AJD0Yej1/m+TXUWu
SaL9AoIBAF8NfL6Sr74pxMLFLgHJiAL8vQLf3wrV9WZFjTDosVlbKir/sPXles0y
JVZVmfnsn6wrFFM8XQrWjC82SWVRmSgugIO7y98e3R0d10pqEzK95leTpcNBsyg3
WZOk8t3+4CyUTu7uW18vRUhU3VGjaIa48X6zlL3sHSUv1zv2K1GmC8oGeSi1C2Ax
GrxW+1dH3xBRcJNufBsHyq22mEU/QDExeLhRQBfJN2B+Oogq1f9tX/54uvf3g9SM
8xdcKZ0szUu866nEZj2FP68rVy/+fL1hfv9HKbyCQWbywblJQHfI+0iAUcg+WCau
5G1SlJDYOB3bEIcxAei4hXTg7mDkQ6ECggEAJu5rkEHOJGoIHe9T5+AmIvNp3iOL
2rsa72iO4VWkSm4QsXqT5J8pmHtk69EFEV8a9pb79wr4cu0yxlcZH7Tw5d3nMFr1
fhYcQCwpHWF6/CepdU3QlOuJty/y6m6AhUK2aDQV1nO8xsKsRfCN/noVPPLDYzri
UeJF3xUxRIoRpcwdWqphMZEBnV9HNyMPngFiud6ofQ6uhadbYLH3bH78dNljxdsv
iVIM1ngYMf2KTDW0R2KrHh6lcjfzc+zphWZksQFRzO3DGNpRj1i5StsAN+OyOIP4
Aogui+WPGkHFqAEWKORFJ1rRq2EZWt48p7AySxXlQm/vXoIgCmBdUW3SGA==
-----END RSA PRIVATE KEY-----
''',
    # "OAUTH2_VALIDATOR_CLASS": "oauth2_provider.oauth2_validators.OAuth2Validator",
    "OAUTH2_VALIDATOR_CLASS": "account.oauth2_validators.CustomOAuth2Validator",
    "OIDC_ID_TOKEN_EXPIRATION": 3600,
    "PKCE_REQUIRED": True,
    "SCOPES": {
        "openid": "OpenID Connect scope",
        "profile": "User profile scope",
        "email": "User email scope",
        "groups": "User groups scope",
    },
}

# CORS

CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# EMAIL

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = getenv('DEFAULT_FROM_EMAIL')
EMAIL_HOST = getenv('EMAIL_HOST')
EMAIL_PORT = getenv('EMAIL_PORT')
EMAIL_HOST_USER = getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = getenv('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

# Application definition
DOMAIN_NAME = getenv('DOMAIN_NAME')
API_VERSION = 'v1'

# URLS
API_URL = 'https://' + DOMAIN_NAME + '/api/' + API_VERSION + '/'
HOME_URL = getenv('HOME_URL')
TERMS_URL = getenv('TERMS_URL')
PRIVACY_URL = getenv('PRIVACY_URL')
CONTACT_URL = getenv('CONTACT_URL')

# CDN
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': getenv('CLOUD_NAME'),
    'API_KEY': getenv('API_KEY'),
    'API_SECRET': getenv('API_SECRET')
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
